separator = "▏"
separator_color = "red"
key_color = "red"
hide_ascii = true
prefer_small_ascii = true

[palette]
type = "Dark"
visible = true
glyph = "  "

[box]
title = " othi "
border = "plain"
visible = true

[bar]
glyph = "▮ "
hide_delimiters = true
visible = true

[randomize]
key_color = false
separator_color = false

[custom_ascii]
color = "red"
path = "~/.config/macchina/themes/ascii-arch.txt"

[keys]
host = "󰍹 host"
kernel = " kernel"
distro = "󱄅 distro"
de = " desktop"
packages = " packages"
terminal = " terminal"
shell = " shell"
cpu = " cpu"
cpu_load = " cpu"
memory = " memory"
uptime = " uptime"
resolution = "󰆾 resolution"
