#! /usr/bin/env bash

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"

  run() {
    $EWW_BIN -c $EWW_CONF open calendar
  }

  if [[ ! -f "$LOCK_FILE" ]]; then
    # ${EWW_BIN} -c $HOME/.config/eww close others
    touch "$LOCK_FILE"
    run && echo "ok good!"
  else
    $EWW_BIN -c $EWW_CONF close calendar
    echo $EWW_BIN
    rm "$LOCK_FILE" && echo "closed"
  fi
}


echo $S1
calendar

if [ "$S1" = "calendar" ]; then
  calendar
fi
