# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
#
# for new machines: get encrypted age from
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt
# age-keygen -y ~/.config/sops/age/keys.txt
keys:
  - &laptop_work age1lc25kk22tnmp927s6wqfc307vfkvg97zxtfwlh5laesnkja75u2qpa2et6
  - &pc_main age1yjwnyw0adud0efyyne0mmhe3j5e60cewfc0rs7j8utnfzt7phdds2dfy4t
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *laptop_work
          - *pc_main
