[manager]
prepend_keymap = [
  # Hopping
  { on = "l", run = "arrow prev", desc = "Previous file" },
  { on = "n", run = "arrow next", desc = "Next file" },
  # Seeking
  { on = "L", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "N", run = "seek 5", desc = "Seek down 5 units in the preview" },
  # Navigation
  { on = "e", run = "enter", desc = "Enter the child directory" },
  { on = "E", run = "forward", desc = "Forward to next directory" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Back to git root" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  # drag-n-drop support
  { on = "<C-n>", run = '''
      shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
  ''' },
]

[tasks]
prepend_keymap = [
  { on = "l", run = "arrow prev", desc = "Previous task" },
  { on = "n", run = "arrow next", desc = "Next task" },
]

[spot]
prepend_keymap = [
  { on = "l", run = "arrow prev", desc = "Previous line" },
  { on = "n", run = "arrow next", desc = "Next line" },
  { on = "h", run = "swipe prev", desc = "Swipe to previous file" },
  { on = "l", run = "swipe next", desc = "Swipe to next file" },
]

[confirm]
prepend_keymap = [
  { on = "l", run = "arrow prev", desc = "Previous line" },
  { on = "n", run = "arrow next", desc = "Next line" },
]

[cmp]
prepend_keymap = [
  { on = "<A-l>", run = "arrow prev", desc = "Previous item" },
  { on = "<A-n>", run = "arrow next", desc = "Next item" },
]

[help]
prepend_keymap = [
  # Navigation
  { on = "l", run = "arrow prev", desc = "Previous line" },
  { on = "n", run = "arrow next", desc = "Next line" },
]
